### ISSUE TITLE
Error: Docker run failed with exit code 126

### ISSUE THREAD

**Issue by madiedgar** [wescran/commit-issue-action#27]
Thanks so much for creating this. It's been extremely useful for `tree-sitter-legesher-python` 😄 

Trying to use it for `language-legesher-python` but am running into this error. Do I need to initialize anything for docker? Thank you!

```shell 
/usr/bin/docker run --name ee625f170e0f3225ffece70b687f1abc606_668e99 --label 671ee6 --workdir /github/workspace --rm -e GITHUB_TOKEN -e INPUT_SOURCEREPO -e INPUT_TARGETREPO -e INPUT_ISSUELABELS -e HOME -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e GITHUB_ACTIONS=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/language-legesher-python/language-legesher-python":"/github/workspace" 671ee6:25f170e0f3225ffece70b687f1abc606  "atom/language-python" "legesher/language-legesher-python" ":construction: Opportunity: Maintenance, Status: Available, Status: Review Needed"
/usr/bin/docker: Error response from daemon: OCI runtime create failed: container_linux.go:346: starting container process caused "exec: \"/entrypoint.sh\": permission denied": unknown.
##[error]Docker run failed with exit code 126
```

**Comment by wescran** [comment]
I will take a look at this and get back to you!

**Comment by wescran** [comment]
@madiedgar The issue is that the `entrypoint.sh` script hasn't been made executable. It's permissions right now are 664 and they need to be at least 775. When new files are made, they are never given the proper permissions to be executable which is probably what happened. I will add this to the docs, thanks for bringing this to my attention!

Basically all that needs to happen is in your terminal use the `chmod` command to add executable permissions to the file. I also have a fork of the repo and can create a PR with the changes if you would like?

**Comment by madiedgar** [comment]
Makes a lot of sense @wescran, thank you for the explanation! 

That would be lovely - creating a PR with the changes would be extremely helpful. Thanks again @wescran!
